"""
VibeSec Backend - Pull Request Service

Create GitHub PRs with security fixes.
"""

import base64
from typing import Optional
from app.services.github import GitHubService


async def create_fix_pr(
    github: GitHubService,
    owner: str,
    repo: str,
    branch: str,
    file_path: str,
    original_content: str,
    fixed_content: str,
    finding_title: str,
    finding_id: int,
) -> dict:
    """
    Create a GitHub PR with a security fix.
    
    Args:
        github: GitHub service with user's access token
        owner: Repository owner
        repo: Repository name
        branch: Base branch (e.g., 'main')
        file_path: Path to the file to fix
        original_content: Original file content
        fixed_content: Fixed file content
        finding_title: Title of the security finding
        finding_id: ID of the finding
        
    Returns:
        PR creation response with URL
    """
    # Generate unique branch name
    fix_branch = f"vibesec/fix-{finding_id}"
    
    # Get the base branch SHA
    base_ref = await github.get_ref(owner, repo, f"heads/{branch}")
    base_sha = base_ref["object"]["sha"]
    
    # Create new branch
    try:
        await github.create_ref(owner, repo, f"refs/heads/{fix_branch}", base_sha)
    except Exception:
        # Branch might already exist, try to update it
        pass
    
    # Get current file SHA
    current_file = await github.get_contents(owner, repo, file_path, branch)
    file_sha = current_file.get("sha")
    
    # Update file with fix
    commit_message = f"fix: {finding_title}\n\nApplied by VibeSec (finding #{finding_id})"
    
    await github.create_commit(
        owner=owner,
        repo=repo,
        path=file_path,
        message=commit_message,
        content=base64.b64encode(fixed_content.encode()).decode(),
        sha=file_sha,
        branch=fix_branch,
    )
    
    # Create PR
    pr_title = f"🔒 Security Fix: {finding_title}"
    pr_body = f"""## Security Fix Applied by VibeSec

This PR addresses a security vulnerability detected during automated scanning.

### Finding Details
- **ID**: #{finding_id}
- **Title**: {finding_title}

### Changes Made
This fix was automatically generated by VibeSec's AI-powered remediation engine.

---
*Created by [VibeSec](https://vibesec.dev) - Security for AI-generated code*
"""
    
    pr = await github.create_pull_request(
        owner=owner,
        repo=repo,
        title=pr_title,
        body=pr_body,
        head=fix_branch,
        base=branch,
    )
    
    return {
        "pr_number": pr["number"],
        "pr_url": pr["html_url"],
        "branch": fix_branch,
    }


async def apply_batch_fixes(
    github: GitHubService,
    owner: str,
    repo: str,
    branch: str,
    fixes: list[dict],
) -> dict:
    """
    Apply multiple fixes in a single PR.
    
    Args:
        github: GitHub service
        owner: Repository owner
        repo: Repository name
        branch: Base branch
        fixes: List of fixes, each with file_path, fixed_content, finding_title, finding_id
        
    Returns:
        PR creation response
    """
    if not fixes:
        return {"error": "No fixes to apply"}
    
    # Generate batch branch name
    fix_branch = f"vibesec/batch-fix-{len(fixes)}-issues"
    
    # Get the base branch SHA
    base_ref = await github.get_ref(owner, repo, f"heads/{branch}")
    base_sha = base_ref["object"]["sha"]
    
    # Create new branch
    try:
        await github.create_ref(owner, repo, f"refs/heads/{fix_branch}", base_sha)
    except Exception:
        pass
    
    # Apply each fix
    applied = []
    for fix in fixes:
        try:
            # Get current file
            current_file = await github.get_contents(owner, repo, fix["file_path"], fix_branch)
            
            # Commit fix
            await github.create_commit(
                owner=owner,
                repo=repo,
                path=fix["file_path"],
                message=f"fix: {fix['finding_title']}",
                content=base64.b64encode(fix["fixed_content"].encode()).decode(),
                sha=current_file.get("sha"),
                branch=fix_branch,
            )
            applied.append(fix["finding_id"])
        except Exception as e:
            pass  # Continue with other fixes
    
    # Create PR
    finding_ids = ", ".join([f"#{fid}" for fid in applied])
    pr_title = f"🔒 Security Fixes: {len(applied)} issues resolved"
    pr_body = f"""## Batch Security Fixes by VibeSec

This PR addresses {len(applied)} security vulnerabilities.

### Findings Fixed
{finding_ids}

---
*Created by [VibeSec](https://vibesec.dev)*
"""
    
    pr = await github.create_pull_request(
        owner=owner,
        repo=repo,
        title=pr_title,
        body=pr_body,
        head=fix_branch,
        base=branch,
    )
    
    return {
        "pr_number": pr["number"],
        "pr_url": pr["html_url"],
        "branch": fix_branch,
        "fixes_applied": len(applied),
    }
